Added support for Pods file field
pods-framework/pods-caldera-forms pull request #12
Opened 2016-07-15 14:18 UTC by romci

2016-07-15 14:56 UTC, Desertsnowman commented
I'll take a look at this on Monday morning.

2017-06-01 19:19 UTC, sc0ttkclark requested changes

2017-06-01 19:19 UTC, sc0ttkclark commented on includes/functions.php
> +				if ($real_pod_field["type"] == "file") {
@romci You should use `$file_field_types = PodsForm::file_field_types();` and then `if ( $real_pod_field && in_array( $real_pod_field['type'], $file_field_types, true ) )`

2017-06-01 19:19 UTC, sc0ttkclark commented on includes/functions.php
> +					if (file_exists($orig_file_path)&&!is_dir($orig_file_path)&&rename($orig_file_path, $tmp_file_path)) {;
@Shelob9 Does Caldera Forms not have some sort of function or method that can be used to handle this type of logic, or is the above necessary to reproduce it for each integration?

2020-02-10 03:52 UTC, closed without merging